FROM golang:alpine

# Set necessary environmet variables needed for our image
ENV GO111MODULE=on \
    CGO_ENABLED=0 \
    GOOS=linux \
    GOARCH=amd64 \
    SQLSERVER=*servernameorip* \
    SQLUSER=*username* \
    SQLPW=*password* \
    SQLPORT=*port* \
    SQLDBNAME=*dbname*

# Creat app directory
RUN mkdir /app

# Copy the code into the container
COPY . /app

# Set work directory
WORKDIR /app

# Build the application
RUN go build -o main .

# Export necessary port
EXPOSE 3000

# Command to run when starting the container
CMD ["/app/main"]